- name: ensure postgres and psycopg2 are installed
  apt: name={{ item }} state=present
  with_items:
  -  postgresql
  -  postgresql-contrib
  -  libpq-dev
  -  python-psycopg2

- name: make configuration in pg_hba.conf
  replace: >
      dest=/etc/postgresql/9.4/main/pg_hba.conf
      regexp='^(local\s+)all(\s+all\s+peer)$'
      replace='\1sameuser\2'
  notify:
  - reload postgresql

- name: ensure postgres database exists
  sudo: yes
  sudo_user: postgres
  postgresql_db: >
    name={{ postgres_db }}
    state=present
    template=template0
    encoding=UTF8
    lc_collate=en_US.UTF-8
    lc_ctype=en_US.UTF-8

- name: ensure postgres user exists
  sudo_user: postgres
  postgresql_user: >
        name={{ postgresql_user }}
        state=present



