-   name: ensure uwsgi and its python plugin are installed
    apt: name={{ item }} state=present
    with_items:
    -   uwsgi
    -   uwsgi-plugin-python

-   name: ensure correct configuration in /etc/default/uwsgi
    lineinfile: >
        state=present
        dest=/etc/default/uwsgi
        line='export LANG=en_US.UTF-8'
        insertafter=EOF
    notify:
    -   restart uwsgi

-   name: ensure uwsgi configuration is deployed in apps-available
    template: >
        dest=/etc/uwsgi/apps-available/{{ uwsgi_app }}.ini
        src=../templates/uwsgi.ini
    notify:
    -   restart uwsgi

-   name: ensure uwsgi configuration is symlinked to apps-enabled
    sudo_user: root
    file: >
        src=/etc/uwsgi/apps-available/{{ uwsgi_app }}.ini
        path=/etc/uwsgi/apps-enabled/{{ uwsgi_app }}.ini
        state=link
    notify:
    -   restart uwsgi
